### ISSUE TITLE
No links to files created today

### ISSUE THREAD

**Issue by ontrou** [trydalch/obsidian-daily-activity#9] opened 2021-02-21 15:53 UTC
The new date range options in plugin v0.1.1. works so well, on ALL my notes going back nearly 10 years. So very pleased about this.

However, all notes are listed as 'modified'. I have no 'created today' notes. The notes I did create today to test the plugin are listed as 'modified'.

EDIT: This is true for all 3 commands.... Links to Files Created Today, Links to Files Modified Today, Stats for date

**Comment by trydalch** [comment] 2021-02-22 16:43
That's interesting, all three work for me. Perhaps it's an OS compatibility issue. What OS are you running? Has it always been like this, or is it only since the v0.1.1

**Comment by ontrou** [comment] 2021-02-22 17:49
Linux - and this has only been an issue with v0.1.1. All files are listed as modified; no files are listed as created, for every date, date range I've selected.

**Comment by trydalch** [comment] 2021-02-22 22:18
@ontrou I'm unable to reproduce on Ubuntu 20.04. I'm seeing the expected functionality. 

Have you tried uninstalling the plugin and reinstalling it?

**Comment by ontrou** [comment] 2021-02-23 03:25
OK, so rebooted my computer, with a fresh install of obsidian (appimage), reinstalled your plugin now at v0.2.2, no other third-party plugins. I get the same results. ..all newly created files are lists as modified files.

I did notice that when I hover over the file listing in Obsidian's file explorer, all files have a creation date of 1969. Does that mean something?

![Screenshot from 2021-02-22 22-10-23](https://user-images.githubusercontent.com/77127294/108798729-885a6a80-755c-11eb-985c-b0c40405d58f.png)

Thanks for investigating.

**Comment by trydalch** [comment] 2021-02-23 05:06
That's the Unix Epoch time (Linux uses epoch time stamps, which are basically a count of seconds since 1970). 

It sounds like something went through and wiped the creation time off of your files. Do files outside of your vault have creation time stamps?

If you uninstall this plugin, and then create a new file, does it have the proper time stamp?

**Comment by trydalch** [comment] 2021-02-23 17:13
I guess it could also be that Obsidian.md is no longer reading the timestamp correctly (this plugin just gets the file timestamps from Obsidian rather than directly from the file system).

If you view the files in a file explorer, or a terminal (navigate to the directory, run `ls -l`, do you see the creation time?

**Comment by ontrou** [comment] 2021-02-23 20:38
> It sounds like something went through and wiped the creation time off of your files. Do files outside of your vault have creation time stamps?

Well..gulp. The files outside my Obsidian vault also have "unknown" creation times (downloaded files e.g. epubs, pdfs _do_ have creation dates). 

> If you uninstall this plugin, and then create a new file, does it have the proper time stamp?

No. It still shows "1969-12-31.." in Obsidian.

> If you view the files in a file explorer, or a terminal (navigate to the directory, run `ls -l`, do you see the creation time?

`ls -l` shows modifed dates (which is expected, no?). In Nemo I see the correct modified dates and "unknown" creation dates. But I've learned that Nemo uses the `ctime` - _the last time when the attributes of a file were changed_. What exactly does Obsidian use?

> I guess it could also be that Obsidian.md is no longer reading the timestamp correctly (this plugin just gets the file timestamps from Obsidian rather than directly from the file system).

I was given advice that creation date in Linux is not easily accessible, and that I should run `debugfs -R 'stat <inode_number>' DEVICE` to find the creation date. I encountered `Bad magic number in super-block" when I did that. So figuring that out will have to wait until tomorrow.

Thanks for your patience and advice. I think the real question is why did your plugin work on my Linux machine, and then suddenly stop.

**Comment by trydalch** [comment] 2021-02-23 23:04
IMO that sounds like a system issue. Perhaps a recent OS update, or package update, and not specific to Obsidian. 

Hope you can get it figured out! For now, I'm going to close this ticket. Feel free to reopen it if you discover that the issue is the plugin.

**Closed as completed by trydalch** 2021-02-23 23:04 UTC
